[package]
name = "panod"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true
repository.workspace = true
description = "Panora clipboard daemon"

[lib]
name = "panod"
path = "src/lib.rs"

[[bin]]
name = "panod"
path = "src/main.rs"

[dependencies]
panora-core = { path = "../panora-core" }
tokio = { workspace = true, features = ["process"] }
async-trait.workspace = true
anyhow.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
x11rb.workspace = true
zbus.workspace = true
blake3.workspace = true
futures.workspace = true
image.workspace = true

[target.'cfg(unix)'.dependencies]
oo7.workspace = true
wayland-client.workspace = true
wayland-protocols.workspace = true
wayland-protocols-wlr.workspace = true
rustix = { version = "1", features = ["event", "fs", "pipe", "process"] }

[dev-dependencies]
tempfile = "3"
criterion.workspace = true

[[bench]]
name = "ipc"
harness = false
