// Copyright (C) 2026 Panora contributors
// SPDX-License-Identifier: GPL-3.0-only

//! Minimal string catalogue for the GUI and CLI (`ui.language` in config).
//!
//! Two catalogues are compiled in; no gettext runtime dependency. `system`
//! resolves through the usual `LC_ALL` / `LC_MESSAGES` / `LANG` chain.

/// Supported interface languages.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Language {
    /// Türkçe.
    Turkish,
    /// English.
    English,
}

impl Language {
    /// Resolve the configured language (`system`, `tr`, `en`).
    pub fn from_config(value: &str) -> Self {
        match value.trim().to_ascii_lowercase().as_str() {
            "tr" | "tr_tr" | "turkish" => Language::Turkish,
            "en" | "en_us" | "en_gb" | "english" => Language::English,
            _ => Self::from_environment(),
        }
    }

    /// Detect from the process locale environment. Turkish locales select
    /// Turkish; everything else falls back to English.
    pub fn from_environment() -> Self {
        for var in ["LC_ALL", "LC_MESSAGES", "LANG", "LANGUAGE"] {
            if let Ok(value) = std::env::var(var) {
                if let Some(lang) = Self::from_locale(&value) {
                    return lang;
                }
            }
        }
        Language::English
    }

    /// Parse a locale string such as `tr_TR.UTF-8` or `en_US:en`.
    pub fn from_locale(value: &str) -> Option<Self> {
        let first = value.split(':').next()?.trim();
        if first.is_empty() || first == "C" || first == "POSIX" {
            return None;
        }
        let code = first
            .split(['_', '.', '@', '-'])
            .next()
            .unwrap_or("")
            .to_ascii_lowercase();
        match code.as_str() {
            "tr" => Some(Language::Turkish),
            "" => None,
            _ => Some(Language::English),
        }
    }

    /// Stable config form.
    pub fn code(self) -> &'static str {
        match self {
            Language::Turkish => "tr",
            Language::English => "en",
        }
    }

    /// The string catalogue for this language.
    pub fn strings(self) -> &'static Strings {
        match self {
            Language::Turkish => &TR,
            Language::English => &EN,
        }
    }
}

// The `Strings` struct, `EN` and `TR` are generated by `build.rs`
// from `po/panora.pot` and `po/tr.po`.
include!(concat!(env!("OUT_DIR"), "/catalogue.rs"));

/// Replace the first `{key}` placeholder with `value`.
pub fn fill(template: &str, key: &str, value: &str) -> String {
    template.replacen(&format!("{{{key}}}"), value, 1)
}

/// Pick the plural form for `count` (CLDR calls this the "one" vs. "other"
/// category; English is the only currently-supported language where the
/// wording actually differs -- `1 item` vs. `5 items` -- so the singular
/// catalogue entry is used exactly when `count` is `1` or `-1`, matching
/// CLDR's `one` rule for English, and every other value uses `other`.
/// Turkish nouns do not inflect for count, so both catalogue entries for a
/// pluralizable key hold the same Turkish text; a language whose plural
/// rule needs more than two categories (Russian, Polish, Arabic, ...) will
/// need this function extended, not just a translated catalogue entry.
pub fn pluralize(count: i64, one: &'static str, other: &'static str) -> &'static str {
    if count == 1 || count == -1 {
        one
    } else {
        other
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn locale_parsing() {
        assert_eq!(
            Language::from_locale("tr_TR.UTF-8"),
            Some(Language::Turkish)
        );
        assert_eq!(
            Language::from_locale("en_US.UTF-8"),
            Some(Language::English)
        );
        assert_eq!(Language::from_locale("de_DE"), Some(Language::English));
        assert_eq!(Language::from_locale("C"), None);
        assert_eq!(Language::from_locale(""), None);
        assert_eq!(Language::from_locale("tr:en"), Some(Language::Turkish));
    }

    #[test]
    fn config_codes() {
        assert_eq!(Language::from_config("tr"), Language::Turkish);
        assert_eq!(Language::from_config("EN"), Language::English);
        assert_eq!(Language::Turkish.code(), "tr");
    }

    #[test]
    fn fill_replaces_placeholder() {
        assert_eq!(fill("{n} kayıt", "n", "3"), "3 kayıt");
        assert_eq!(
            fill(EN.no_results_description, "q", "x"),
            "Nothing matches “x”."
        );
    }

    #[test]
    fn every_template_entry_has_a_turkish_translation() {
        // `build.rs` refuses to generate a catalogue with a missing or
        // empty entry, so reaching this test already proves it; the test
        // states the invariant where a reader looks for it and catches a
        // template and a translation that drifted apart in size.
        let template = include_str!("../../../po/panora.pot");
        let turkish = include_str!("../../../po/tr.po");
        let contexts = |text: &str| {
            text.lines()
                .filter(|line| line.starts_with("msgctxt "))
                .count()
        };
        assert_eq!(contexts(template), contexts(turkish));
        // The header is the one entry with an empty `msgstr`; skip past it.
        let body = turkish.split_once("\nmsgctxt ").expect("no entries").1;
        assert!(
            !body.lines().any(|line| line == "msgstr \"\""),
            "untranslated entry in tr.po"
        );
    }

    #[test]
    fn pluralize_picks_the_singular_form_only_at_plus_or_minus_one() {
        assert_eq!(pluralize(1, "one", "other"), "one");
        assert_eq!(pluralize(-1, "one", "other"), "one");
        assert_eq!(pluralize(0, "one", "other"), "other");
        assert_eq!(pluralize(2, "one", "other"), "other");
        assert_eq!(pluralize(-2, "one", "other"), "other");
    }

    #[test]
    fn catalogue_plural_pairs_read_correctly_in_both_languages() {
        for strings in [&EN, &TR] {
            assert_eq!(
                pluralize(1, strings.subtitle_count_one, strings.subtitle_count),
                strings.subtitle_count_one
            );
            assert_eq!(
                pluralize(5, strings.subtitle_count_one, strings.subtitle_count),
                strings.subtitle_count
            );
        }
        // English distinguishes the two; Turkish does not need to.
        assert_ne!(EN.subtitle_count_one, EN.subtitle_count);
        assert_eq!(TR.subtitle_count_one, TR.subtitle_count);
    }

    #[test]
    fn catalogues_have_no_empty_strings() {
        for strings in [&TR, &EN] {
            let dump = format!("{strings:?}");
            assert!(!dump.contains("\"\""), "empty string in catalogue");
        }
    }
}
